import {cookingDefaults,submitCooking,temperatureCheckContext,submitTemperatureCheck,expiryContext,submitExpiry,canStartHotFood,getOverdueTemperatureTasks} from './hot-food-engine.js';

const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const nowHM=()=>new Date().toTimeString().slice(0,5);
function modal(title,body,confirmText='Confirm & Complete'){
  return new Promise(resolve=>{const wrap=document.createElement('div');wrap.className='modal-overlay hf-modal-overlay';wrap.innerHTML=`<div class="modal hf-modal"><h2>${esc(title)}</h2><div class="hf-modal-body">${body}</div><div class="modal-actions"><button class="btn secondary hf-cancel">Go Back</button><button class="btn hf-confirm">${esc(confirmText)}</button></div></div>`;document.body.append(wrap);document.body.classList.add('modal-open');const done=v=>{wrap.remove();document.body.classList.remove('modal-open');resolve(v)};wrap.querySelector('.hf-cancel').onclick=()=>done(null);wrap.addEventListener('click',e=>{if(e.target===wrap)done(null);const add=e.target.closest?.('.hf-add-retest');if(add){const box=add.parentElement.querySelector('.hf-core-readings');const i=document.createElement('input');i.className='hf-temp';i.type='number';i.step='0.1';i.placeholder='Retest °C';box.append(i);i.focus();}const addProduct=e.target.closest?.('.hf-add-product-btn');if(addProduct){const select=wrap.querySelector('.hf-add-product-select');const row=select?.value?wrap.querySelector(`.hf-cook-row[data-id="${CSS.escape(select.value)}"]`):null;if(row){row.hidden=false;row.querySelector('.hf-use').checked=true;row.scrollIntoView({behavior:'smooth',block:'nearest'});select.value='';}}});wrap.addEventListener('change',e=>{if(e.target.matches?.('.hf-no-cooking')){const off=e.target.checked;wrap.querySelectorAll('.hf-cook-row').forEach(r=>{r.classList.toggle('hf-disabled',off);r.querySelectorAll('input,button').forEach(el=>el.disabled=off);});}});wrap.querySelector('.hf-confirm').onclick=()=>done(wrap);});
}
function selectedItems(root){return [...root.querySelectorAll('.hf-cook-row')].filter(r=>r.querySelector('.hf-use').checked).map(r=>{const coreReadings=[...r.querySelectorAll('.hf-temp')].map(i=>Number(i.value)).filter(Number.isFinite);return {productId:r.dataset.id,productName:r.dataset.name,qty:+r.querySelector('.hf-qty').value,coreTempC:coreReadings.at(-1),coreReadings,wasteFailed:r.querySelector('.hf-failed-waste').checked};});}
function depletedBatchSellOuts(product,currentQty){let sold=Math.max(0,Number(product.currentSystemQty)-Number(currentQty)),out=[];for(const b of product.batches||[]){const rem=Number(b.remainingQty)||0;if(sold>=rem&&rem>0){out.push(b);sold-=rem;}else break;}return out;}
async function collectSellOutTimes(ctx,root,actualTime){for(const row of root.querySelectorAll('.hf-temp-row')){const p=ctx.products.find(x=>x.productId===row.dataset.id);if(!p)continue;const depleted=depletedBatchSellOuts(p,+row.querySelector('.hf-current').value);row._sellOutTimes={};for(const b of depleted){const label=`${p.productName} batch cooked ${b.timeOutOven}`;const value=prompt(`${label} has sold out under FIFO. Enter Sell Out Time (HH:MM).`,actualTime);if(value===null)throw new Error('Sell Out Time is required for a batch that sold out.');row._sellOutTimes[b.id]=value;}}}
export async function openCookingTask(task,actor,{source}={}){
  const initial=task?.hotFoodType==='cooking_initial'||source==='start_hot_food', d=await cookingDefaults(task.date,initial?'initial':'second');
  const planned=new Map(d.planned.map(x=>[x.productId,x.qty]));
  const ordered=[...d.products].sort((a,b)=>(planned.has(b.id)?1:0)-(planned.has(a.id)?1:0)||String(a.name||'').localeCompare(String(b.name||'')));
  const rows=ordered.map(p=>`<div class="hf-cook-row ${planned.has(p.id)?'planned':''}" ${initial&&!planned.has(p.id)?'hidden':''} data-id="${esc(p.id)}" data-name="${esc(p.name)}"><label class="hf-product-check"><input class="hf-use" type="checkbox" ${planned.has(p.id)?'checked':''}> <span><b>${esc(p.name)}</b>${planned.has(p.id)?'<small>Today\'s plan</small>':''}</span></label><label>Qty<input class="hf-qty" type="number" min="0" step="1" value="${planned.get(p.id)||''}"></label><label>Core temperature °C<div class="hf-core-readings"><input class="hf-temp" type="number" step="0.1" placeholder="75.0"></div><button type="button" class="btn secondary small hf-add-retest">+ Reheat / Retest</button></label><label class="hf-failed-waste-label"><input class="hf-failed-waste" type="checkbox"> Waste if final reading fails</label></div>`).join('');
  const heading=initial?'Initial Cooking':'New Cooking / Top Up';
  const intro=initial?'Today\'s planned products are already selected. Change quantities or untick anything you are not cooking.':'Select what you are cooking now.';
  const root=await modal(heading,`<div class="hf-note"><b>${esc(intro)}</b><br>Record what was actually cooked. Core temperature standard applies to every selected product.</div><label class="hf-time-label">Time Out Oven<input class="hf-time" type="time" value="${nowHM()}"></label><div class="hf-cook-grid">${rows||'<p>No active Hot Food products. Ask a manager to add products first.</p>'}</div>${initial&&d.products.some(p=>!planned.has(p.id))?`<div class="hf-add-product"><select class="hf-add-product-select"><option value="">Add another product…</option>${d.products.filter(p=>!planned.has(p.id)).map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('')}</select><button type="button" class="btn secondary hf-add-product-btn">+ Add Product</button></div>`:''}<label class="hf-no-cook"><input type="checkbox" class="hf-no-cooking"> <span><b>No cooking required today</b><small>Close the scheduled Hot Food tasks for now. Start Hot Food will remain available before 14:00 if cooking starts later.</small></span></label>`,initial?'Confirm Cooking':'Confirm Cooking');
  if(!root)return false;
  const noBox=root.querySelector('.hf-no-cooking');
  const no=noBox.checked,time=root.querySelector('.hf-time').value;
  await submitCooking({date:task.date,taskId:task.id||'',actor,timeOutOven:time,items:selectedItems(root),noCooking:no,source:source||task.hotFoodType});return true;
}
export async function openTemperatureTask(task,actor){
  const overdue=await getOverdueTemperatureTasks(task.date,task); const taskIds=overdue.length?overdue.map(x=>x.id):[task.id]; const scheduledTimes=overdue.length?overdue.map(x=>x.sourceTime):[task.sourceTime];
  const ctx=await temperatureCheckContext(task.date,task.sourceTime); if(!ctx.products.length)throw new Error('No eligible active Hot Food products for this check.');
  const rows=ctx.products.map(p=>`<div class="hf-temp-row" data-id="${esc(p.productId)}" data-name="${esc(p.productName)}"><div><b>${esc(p.productName)}</b><small>System stock: ${p.currentSystemQty}</small></div><label>Current Qty<input class="hf-current" type="number" min="0" step="1" value="${p.currentSystemQty}"></label><label>Lowest °C<input class="hf-reading" type="number" step="0.1" placeholder="${ctx.config.holdingPassC}"></label><label>Waste now<input class="hf-waste" type="number" min="0" step="1" value="0"></label><label>Waste reason<select class="hf-waste-reason"><option value="">—</option><option value="temperature_issue">Temperature issue</option><option value="quality_issue">Quality issue</option><option value="damaged_contaminated">Damaged/contaminated</option><option value="end_of_service">End of service</option><option value="other">Other</option></select></label><label>Comment<input class="hf-waste-comment" placeholder="Required for Other"></label><label>Sell Out Time<input class="hf-sellout" type="time"></label></div>`).join('');
  const root=await modal(`${task.sourceTime} Hot Food Temperature Check`,`<div class="hf-note">${scheduledTimes.length>1?`<b>Catch-up:</b> this genuine current reading will close overdue checks ${scheduledTimes.join(', ')}. It will not create fake historical readings.<br>`:''}<b>Enter the lowest temperature measured.</b> Current Qty means physically on shelf before any new waste/removal. Standard ≥ ${ctx.config.holdingPassC}°C.</div><label>Actual reading time<input class="hf-actual-time" type="time" value="${nowHM()}"></label><div class="hf-temp-grid">${rows}</div>`);if(!root)return false;
  const actualReadingTime=root.querySelector('.hf-actual-time').value;await collectSellOutTimes(ctx,root,actualReadingTime);
  const readings=[...root.querySelectorAll('.hf-temp-row')].map(r=>({productId:r.dataset.id,productName:r.dataset.name,qty:+r.querySelector('.hf-current').value,temperatureC:r.querySelector('.hf-current').value==='0'?null:+r.querySelector('.hf-reading').value,wasteQty:+r.querySelector('.hf-waste').value,wasteReason:r.querySelector('.hf-waste-reason').value,wasteComment:r.querySelector('.hf-waste-comment').value,sellOutTime:r.querySelector('.hf-sellout').value,sellOutTimes:r._sellOutTimes||{}}));
  await submitTemperatureCheck({date:task.date,taskId:task.id,taskIds,actor,scheduledTimes,actualReadingTime,readings});return true;
}
export async function openExpiryTask(task,actor){const b=await expiryContext(task.hotFoodBatchId);const root=await modal(`4-Hour Expiry — ${b.productName}`,`<div class="hf-note">Cooked ${esc(b.timeOutOven)} · System estimated remaining <b>${Number(b.remainingQty)||0}</b><br>Enter what was physically found/removed. If this is greater than the estimate, the discrepancy is retained for Manager review.</div><label>Actual quantity wasted<input class="hf-exp-waste" type="number" min="0" value="${Number(b.remainingQty)||0}"></label><label>Actual removal/waste time<input class="hf-exp-time" type="time" value="${nowHM()}"></label><label>Reason if removed early<select class="hf-exp-reason"><option value="">—</option><option value="temperature_issue">Temperature issue</option><option value="quality_issue">Quality issue</option><option value="damaged_contaminated">Damaged/contaminated</option><option value="end_of_service">End of service</option><option value="other">Other</option></select></label><label>Comment<input class="hf-exp-comment" placeholder="Required for Other"></label><label>Sell Out Time (if waste is 0)<input class="hf-exp-sell" type="time"></label>`);if(!root)return false;await submitExpiry({taskId:task.id,batchId:b.id,actor,actualWasteQty:+root.querySelector('.hf-exp-waste').value,removalTime:root.querySelector('.hf-exp-time').value,sellOutTime:root.querySelector('.hf-exp-sell').value,earlyReason:root.querySelector('.hf-exp-reason').value,earlyComment:root.querySelector('.hf-exp-comment').value});return true;}
export async function completeHotFoodTask(task,actor){if(task.hotFoodType==='temperature_check')return openTemperatureTask(task,actor);if(task.hotFoodType==='expiry')return openExpiryTask(task,actor);return openCookingTask(task,actor);}
export async function renderStartHotFoodButton(date,container,actorProvider){if(!container)return;const ok=await canStartHotFood(date);let b=container.querySelector('#startHotFoodBtn');if(!ok){b?.remove();return;}if(!b){b=document.createElement('button');b.id='startHotFoodBtn';b.className='btn hf-start-btn';b.textContent='Start Hot Food';container.prepend(b);}b.onclick=async()=>{const actor=await actorProvider();if(!actor)return;try{await openCookingTask({id:'',date,hotFoodType:'cooking_initial'},actor,{source:'start_hot_food'});}catch(e){alert(e.message||e)}};}
