import {db,collection,doc,getDoc,getDocs,setDoc,updateDoc,query,where,serverTimestamp} from './firebase.js';
import {getUsers,getStaffAvailability,slotForClock,todayISO} from './store.js';

const CLEANING_DOC='cleaningRotation';
const COMPLIANCE_DOC='complianceConfig';
const DAY={Sun:'sun',Mon:'mon',Tue:'tue',Wed:'wed',Thu:'thu',Fri:'fri',Sat:'sat'};
const DOW=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];
export const CLEANING_EFFECTIVE='2026-10-08';

export const DEFAULT_CLEANING={version:1,effectiveFrom:CLEANING_EFFECTIVE,items:[
 {id:'prashanthy',staffId:'staff3',days:['Mon','Fri'],time:'14:01',mode:'rotate',missingLabels:true,photo:true,areas:['KitKat Bay','Hubba Bay & American Bay','Crisps 1 of 2','Crisps 2 of 2 + Cheetos'],nextIndex:0,active:true},
 {id:'himmo',staffId:'staff7',days:['Tue'],time:'14:01',mode:'rotate',missingLabels:true,photo:true,areas:['Carcare near door','Biscuit','Promotion'],nextIndex:0,active:true},
 {id:'parthy-wed',staffId:'staff1',days:['Wed'],time:'14:01',mode:'rotate',missingLabels:true,photo:true,areas:['Butter Chiller (Bottom to Top)','Coke Chiller (Bottom to Top)','2L Drink Bay','Wines Chiller','Beers Chiller'],nextIndex:0,active:true},
 {id:'suku',staffId:'staff4',days:['Thu'],time:'14:01',mode:'rotate',missingLabels:true,photo:true,areas:['Cadbury Bay','Car Care, Oil & Medicine'],nextIndex:0,active:true},
 {id:'parthy-sat',staffId:'staff1',days:['Sat'],time:'14:01',mode:'fixed',missingLabels:true,photo:true,areas:['Milk Chiller'],nextIndex:0,active:true},
 {id:'rishi-sat',staffId:'staff8',days:['Sat'],time:'18:01',mode:'fixed',missingLabels:true,photo:true,areas:['Behind the Till Shelf'],nextIndex:0,active:true},
 {id:'moon-sun',staffId:'staff6',days:['Sun'],time:'14:01',mode:'rotate',missingLabels:true,photo:true,areas:['Petfood & Household','Grocery','Protein Bar Section + Flapjack'],nextIndex:0,active:true},
 {id:'pragash-sun',staffId:'staff9',days:['Sun'],time:'14:01',mode:'rotate',missingLabels:true,photo:true,areas:['Ambient Wines','Ambient Beers'],nextIndex:0,active:true},
 {id:'uday-sun',staffId:'staff2',days:['Sun'],time:'09:01',mode:'fixed',missingLabels:false,photo:true,areas:['Pump deep clean, Carwash mud, Coal bunker, Canopy & fascia dust off'],nextIndex:0,active:true}
]};

export const DEFAULT_COMPLIANCE={version:1,enabled:true,tempPoints:[
 {id:'icecream',name:'Ice Cream',type:'freezer',limit:-18},{id:'freezer1',name:'Freezer 1 (Upstairs)',type:'freezer',limit:-18},
 {id:'dairy1',name:'Dairy-1 (Drinks)',type:'chilled',limit:5},{id:'dairy2',name:'Dairy-2 (BBER)',type:'chilled',limit:5}
],dailyItems:['Fire Extinguisher','Fire Bucket','Speaker','Pumps','Islands','Entrance Access','Fire Exit','First Aid Box','Shop Floor','Emergency Light','Fuel Stop Button'],weeklyItems:['Vent Pipes','Forecourt Signs','Pumps/Nozzles','Lighting','Smoke Alarm','Rubbish Area','Vapour Recovery','Interceptor'],weeklyStaffId:'staff3',weeklyDay:'Wed',weeklyTime:'14:01',sundayDailyStaffId:'staff2',sfbbOpening:['Your fridges, chilled display equipment and freezers are working properly.','All areas are free from evidence of pest activity.','Hot running water is available at all sinks and hand wash basins.','Probe thermometer is working and probe wipes are available.','Allergen information is accurate for all items on sale.','Food on its Use By date has been thrown away.','Dirty cleaning equipment has been cleaned or thrown away.','Waste has been removed and new bags put into the bins.','Floors are swept and clean.'],sfbbClosing:['Food that needs chilling has been put in the fridge or freezer.','Food left on display is protected and stored safely.','Out-of-date or unsafe food has been removed.','All food contact surfaces and equipment have been cleaned and disinfected.','Used cleaning equipment has been cleaned or disposed of.','Waste has been removed and bins are clean and covered.','Floors and work areas are clean and tidy.','No signs of pest activity are present.','Fridges and freezers are operating correctly.','Doors, windows and food storage areas are secured.']};

async function config(name,defaults){const r=doc(db,'system',name),s=await getDoc(r);if(s.exists())return s.data();await setDoc(r,{...defaults,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});return defaults;}
export const getCleaningConfig=()=>config(CLEANING_DOC,DEFAULT_CLEANING);
export async function getComplianceConfig(){const saved=await config(COMPLIANCE_DOC,DEFAULT_COMPLIANCE);const old='Read and confirm the current SFBB closing checks before closing the site.';if(Array.isArray(saved.sfbbClosing)&&saved.sfbbClosing.length===1&&saved.sfbbClosing[0]===old)return {...saved,sfbbClosing:[...DEFAULT_COMPLIANCE.sfbbClosing]};return saved;}
export async function saveCleaningConfig(items,actor){await setDoc(doc(db,'system',CLEANING_DOC),{version:1,effectiveFrom:CLEANING_EFFECTIVE,items,updatedAt:serverTimestamp(),updatedByName:actor?.name||''},{merge:true});}
export async function saveComplianceConfig(data,actor){await setDoc(doc(db,'system',COMPLIANCE_DOC),{...data,updatedAt:serverTimestamp(),updatedByName:actor?.name||''},{merge:true});}

function dateObj(s){return new Date(s+'T12:00:00');}
function dayName(date){return DOW[dateObj(date).getDay()];}
function occurrences(item,date){let n=0,d=dateObj(CLEANING_EFFECTIVE),end=dateObj(date);while(d<=end){if(item.days.includes(DOW[d.getDay()]))n++;d.setDate(d.getDate()+1);}return Math.max(0,n-1);}
async function audit(type,details,actor='system'){const id=`${Date.now()}_${Math.random().toString(36).slice(2,7)}`;await setDoc(doc(db,'auditEvents',id),{type,details,actor,at:serverTimestamp()});}
async function upsertTask(id,data){const ref=doc(db,'dailyTasks',id),snap=await getDoc(ref);if(snap.exists())return false;await setDoc(ref,{...data,status:'pending',completedAt:null,completedByUserId:'',completedByName:'',adHoc:true,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});return true;}

export async function ensureCleaningTasks(date){const cfg=await getCleaningConfig();if(date<String(cfg.effectiveFrom||CLEANING_EFFECTIVE))return;const day=dayName(date),users=await getUsers(),map=new Map(users.map(u=>[u.id,u]));for(const item of (cfg.items||[])){if(item.active===false||!item.days?.includes(day)||!item.areas?.length)continue;const idx=item.mode==='rotate'?(Number(item.nextIndex||0)+occurrences(item,date))%item.areas.length:0,area=item.areas[idx],u=map.get(item.staffId);let name=`Clean ${area}`;if(item.missingLabels)name+=', place missing labels';if(item.photo)name+=' and send photo';await upsertTask(`clean_${date}_${item.id}`,{date,templateTaskId:'',specialType:'cleaning',reportCategory:'Cleaning',cleaningRuleId:item.id,rotationIndex:idx,taskName:name,slotId:slotForClock(item.time,date),sourceTime:item.time,effortMinutes:15,originalAssignedTo:item.staffId,originalAssignedName:u?.name||'Unassigned',assignedTo:item.staffId,assignedName:u?.name||'Unassigned',photoRequired:Boolean(item.photo),temperatureRequired:false,recurring:true,checkpoint:''});}}

function parseShifts(text){return String(text||'').split(',').map(x=>x.trim()).map(x=>{const m=x.match(/^(\d{1,2}:\d{2})\s*[-–—]\s*(\d{1,2}:\d{2})$/);return m?{start:m[1].padStart(5,'0'),end:m[2].padStart(5,'0')}:null;}).filter(Boolean);}
async function dayWorkers(date){const [a,users]=await Promise.all([getStaffAvailability(),getUsers()]),key=DAY[dayName(date)],rows=[];for(const u of users.filter(x=>x.active!==false&&(x.role==='staff'||x.role==='assignee'))){for(const sh of parseShifts(a?.week?.[u.id]?.[key]||''))rows.push({u,start:sh.start,end:sh.end});}return rows;}
function minusMinutes(hm,n){let [h,m]=hm.split(':').map(Number),x=h*60+m-n;x=Math.max(0,x);return `${String(Math.floor(x/60)).padStart(2,'0')}:${String(x%60).padStart(2,'0')}`;}
export async function ensureComplianceTasks(date){const cfg=await getComplianceConfig();if(cfg.enabled===false)return;const workers=await dayWorkers(date);if(!workers.length)return;const opening=[...workers].sort((a,b)=>a.start.localeCompare(b.start))[0],closing=[...workers].sort((a,b)=>b.end.localeCompare(a.end))[0],starts=[...workers].sort((a,b)=>a.start.localeCompare(b.start));const firstShiftByStaff=[];for(const row of starts){if(!firstShiftByStaff.some(x=>x.u.id===row.u.id))firstShiftByStaff.push(row);}let second=firstShiftByStaff[1]||firstShiftByStaff[0];if(dayName(date)==='Sun'){const x=starts.find(r=>r.u.id===cfg.sundayDailyStaffId);if(x)second=x;}const users=await getUsers(),um=new Map(users.map(u=>[u.id,u]));const add=(suffix,type,title,who,time,effort=10)=>upsertTask(`comp_${date}_${suffix}`,{date,specialType:'compliance',reportCategory:type==='temperature'?'Temperature Log':type==='daily'?'Daily Safety':type==='weekly'?'Weekly Safety':'SFBB',complianceType:type,taskName:title,slotId:slotForClock(time,date),sourceTime:time,effortMinutes:effort,originalAssignedTo:who?.u?.id||who?.id||'',originalAssignedName:who?.u?.name||who?.name||'Unassigned',assignedTo:who?.u?.id||who?.id||'',assignedName:who?.u?.name||who?.name||'Unassigned',photoRequired:false,temperatureRequired:false,recurring:true,checkpoint:''});await add('temp_am','temperature','AM Temperature Check',opening,opening.start,10);await add('temp_pm','temperature','PM Temperature Check',closing,minusMinutes(closing.end,30),10);await add('daily','daily','Daily Safety Check',second,second.start,10);await add('sfbb_open','sfbb_open','SFBB Opening Check',opening,opening.start,5);await add('sfbb_close','sfbb_close','SFBB Closing Check',closing,minusMinutes(closing.end,20),5);if(dayName(date)===cfg.weeklyDay){const u=um.get(cfg.weeklyStaffId);await add('weekly','weekly','Weekly Safety Check',u,cfg.weeklyTime||'14:01',15);}}
export async function ensureSpecialTasksForDate(date){await ensureCleaningTasks(date);await ensureComplianceTasks(date);}

export async function saveComplianceResult(task,user,result){await setDoc(doc(db,'complianceRecords',task.id),{date:task.date,taskId:task.id,type:task.complianceType,taskName:task.taskName,assignedTo:task.assignedTo,assignedName:task.assignedName,completedByUserId:user.id,completedByName:user.name||'',result,completedAt:serverTimestamp(),updatedAt:serverTimestamp()},{merge:true});}
export async function getComplianceRecords(from,to){const s=await getDocs(collection(db,'complianceRecords'));return s.docs.map(d=>({id:d.id,...d.data()})).filter(x=>x.date>=from&&x.date<=to).sort((a,b)=>String(a.date).localeCompare(String(b.date)));}
export async function getAuditEvents(){const s=await getDocs(collection(db,'auditEvents'));return s.docs.map(d=>({id:d.id,...d.data()}));}
export {audit};
export async function ensureSafeUpgrades(){const stateRef=doc(db,'system','safeUpgrades'),state=await getDoc(stateRef);if(!state.data()?.cleaningReplacement20261008){const ref=doc(db,'weeklyTemplates','pm04'),snap=await getDoc(ref);if(snap.exists()){const data=snap.data(),schedule=structuredClone(data.schedule||{});for(const day of Object.keys(schedule)){const dd=schedule[day];if(!Array.isArray(dd?.versions))continue;dd.versions.forEach(v=>{if(v.active!==false&&!v.effectiveTo&&String(v.effectiveFrom||'')<'2026-10-08')v.effectiveTo='2026-10-07';});dd.versions.push({effectiveFrom:'2026-10-08',active:false,slotId:'',assigneeId:'',assigneeKey:'',legacyAssignee:'',effortMinutes:15,sourceTime:''});}await updateDoc(ref,{schedule,updatedAt:serverTimestamp()});}await setDoc(stateRef,{cleaningReplacement20261008:true,updatedAt:serverTimestamp()},{merge:true});}if(!state.data()?.toiletSwap20261012){const ref=doc(db,'weeklyTemplates','pm15'),snap=await getDoc(ref);if(snap.exists()){const data=snap.data(),schedule=structuredClone(data.schedule||{});for(const [day,staffId] of [['Wed','staff1'],['Fri','staff6']]){const dd=schedule[day]||{versions:[]};const versions=Array.isArray(dd.versions)?dd.versions:[];versions.forEach(v=>{if(v.active!==false&&!v.effectiveTo&&String(v.effectiveFrom||'')<'2026-10-12')v.effectiveTo='2026-10-11';});versions.push({effectiveFrom:'2026-10-12',active:true,slotId:'S2',assigneeId:staffId,assigneeKey:'',legacyAssignee:'',effortMinutes:15,sourceTime:'13:45'});schedule[day]={...dd,versions};}await updateDoc(ref,{schedule,updatedAt:serverTimestamp()});}await setDoc(stateRef,{toiletSwap20261012:true,updatedAt:serverTimestamp()},{merge:true});}}
