import {db,collection,doc,getDocs,setDoc,updateDoc,query,where,onSnapshot,serverTimestamp,writeBatch} from "./firebase.js";
const days=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];
export function isoDate(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
export const formatDate=()=>new Date().toLocaleDateString("en-GB",{weekday:"long",day:"numeric",month:"long",year:"numeric"});
function status(t){if(t.status==="completed")return "completed";const x=t.time||"";if(!x||x.includes("min"))return "upcoming";const n=new Date(),m=n.getHours()*60+n.getMinutes();let a=null,b=null;if(x.startsWith("After ")){const r=x.match(/(\d{2}):(\d{2})/);if(r)a=+r[1]*60 + +r[2]}else{const r=[...x.matchAll(/(\d{2}):(\d{2})/g)];if(r[0])a=+r[0][1]*60 + +r[0][2];if(r[1])b=+r[1][1]*60 + +r[1][2]}if(a===null)return "upcoming";if(b!==null&&m>b)return "overdue";if(m>=a)return "due";return "upcoming"}
export async function getUsers(){const s=await getDocs(collection(db,"users"));return s.docs.map(d=>({id:d.id,...d.data()}))}
export async function getWeeklyTemplate(){const s=await getDocs(collection(db,"weeklyTemplates"));return s.docs.map(d=>({id:d.id,...d.data()}))}
export async function ensureTodayTasks(){const date=isoDate(),q=query(collection(db,"dailyTasks"),where("date","==",date)),e=await getDocs(q);if(!e.empty)return;const temp=await getWeeklyTemplate();if(!temp.length)return;const day=days[new Date().getDay()],batch=writeBatch(db);temp.forEach(t=>{const original=t.assignments?.[day]||"";batch.set(doc(db,"dailyTasks",`${date}_${t.id}`),{date,templateTaskId:t.id,taskName:t.taskName,shift:t.shift,time:t.time,originalStaff:original,assignedStaff:original,status:"pending",photoRequired:!!t.photoRequired,completedAt:null,completedBy:null,createdAt:serverTimestamp()})});await batch.commit()}
export function watchTodayTasks(cb){const q=query(collection(db,"dailyTasks"),where("date","==",isoDate()));return onSnapshot(q,s=>cb(s.docs.map(d=>{const t={id:d.id,...d.data()};return {...t,status:status(t)}}).sort((a,b)=>(a.time||"").localeCompare(b.time||""))))}
export async function completeTask(id,staffId){await updateDoc(doc(db,"dailyTasks",id),{status:"completed",completedAt:serverTimestamp(),completedBy:String(staffId)})}
export async function reassignTask(id,staffId){await updateDoc(doc(db,"dailyTasks",id),{assignedStaff:String(staffId),reassignedAt:serverTimestamp()})}
export async function coverShift(off,shift,cover){const date=isoDate(),q=query(collection(db,"dailyTasks"),where("date","==",date)),s=await getDocs(q),rows=s.docs.map(d=>({id:d.id,...d.data()})).filter(t=>String(t.assignedStaff)===String(off)&&t.shift===shift),batch=writeBatch(db);rows.forEach(t=>batch.update(doc(db,"dailyTasks",t.id),{assignedStaff:String(cover),shiftCoverFrom:String(off),shiftCoveredAt:serverTimestamp()}));if(rows.length)await batch.commit();await setDoc(doc(collection(db,"shiftCover")),{date,shift,staffOff:String(off),coveredBy:String(cover),taskCount:rows.length,createdAt:serverTimestamp()});return rows.length}
export const percent=t=>t.length?Math.round(t.filter(x=>x.status==="completed").length/t.length*100):0;
export async function saveUser(id,data){await setDoc(doc(db,"users",id),data,{merge:true})}
